### PR TITLE
Working PR for the update to 0.14.0

### PR DESCRIPTION
**Pull request by mcollina**
* [x] Nscale Introduction
* [x] Exercise 2 - Create a new system
* [x] Exercise 3 - Deploy a larger application
* [x] Exercise 4 - Config & Logs
* [x] Exercise 5 - Update & Rollback
* [x] Exercise 6 - Automatic system fix
* [x] Exercise 7 - Using an image from Docker Hub
* [x] Exercise 8 - Deploying to AWS
* [x] Exercise 9 - Local development workflow, with a mixed container environment
* [x] Deploy directly via SSH - Deploy to an already running machine, this examples is powered by DigitalOcean.
* [x] Move from number files to self-explicatable names

All examples will be pointing to a `v0.14` branch there, to merged together with this one. All the PR referencing this one __must be merged__ for the examples to work.

### CODE REVIEW

**Comment by mcollina** [comment]
It this done? Can you please update the list at the top?

**Comment by darragh-hayes** [comment]
The only thing I can't say is 100% done is the digitalocean exercise. The referral link does not work anymore and I wasn't able to set up an account with them. All I could do was change the nsd commands to nscale. Also the "fixing a bug" exercise has been changed now. We don't have it anymore but one of the other exercises has been made much clearer in how to make changes and redeploy

**Comment by darragh-hayes** [comment]
Maybe I shouldn't have, but I've actually already merged my commits as part of my own PR already..

**Comment by mcollina** [comment]
You did good. Please update the exercise for the 'fix a bug' thing. Ask seamus for a DO account.

**Comment by McDonnellDean** [comment]
@darragh-hayes @mcollina What is the status of this guys? Once this is in I want to do some minor cleanup so we can get a better picture of what belongs in this repo and what belongs in the docs. @pelger I'd like to discuss this repo, what should live here exclusively and what should be linked from the main repo. 

Once we sort this I think it would be a good idea to look at standardising the page layout between here and the docs repo, just so there is no jarring change when moving back and forth between both libs.

**Comment by mcollina** [comment]
As stated in #36, I would love to remove this repo altogether, and move everything into nscale-docs.

Anyway, as things stands we can merge this when v0.14 is released.

**Comment by darragh-hayes** [comment]
In docker-intro.md, There were links to our wiki pages showing Linux and OSX setup guides for docker/boot2docker. I've linked directly to the docker guides instead. The boot2docker-osx guide is a guide for installing off a usb. It's completely useless in the tutorials now so is it okay if I delete it altogether?

**Comment by mcollina** [comment]
For now just remove the link, we'll need when we do the workshop live.
Il giorno ven 20 feb 2015 alle 12:36 Darragh Hayes <notifications@github.com>
ha scritto:

**Comment by McDonnellDean** [comment]
Thanks @mcollina. Given @pelger wants to do a clean up of the docs first I am going to move to that tonight and prepare them for the eventual move.

**Comment by darragh-hayes** [comment]
@pelger is specifically looking to get an extra pair of eyes or two on the tutorials to see if they flow well. If we've missed any problems. From what I can see it's pretty polished!

**Pull request merged**
